### ISSUE TITLE
Update to ubuntu 18.04 lts and add docker-compose

### ISSUE THREAD

**Issue by Enoxime** [AuchanDirect/docker-forticlient#4]
Hi,

I was looking for a good forticlient dockerized and found yours. I use it for two days now and made some changes to adapt my needs. I update Ubuntu and add a docker-compose.
With my change, in a GNU/Linux, it works without the docker network.
Is your repository still alive ? If yes, I will pull request my changes.

**Comment by Enoxime** [comment]
My bad, I close the wrong issue.

**Comment by mrjmad** [comment]
Hello, I transfer the ownership of the repository but it is still alive. 

go for your PR  ! ;)

**Comment by Enoxime** [comment]
Thank you. I'll do it Monday. The only thing is about the ppp, I can't test on a Mac because I don't own any.

**Comment by Enoxime** [comment]
Finally I get time today to create the pull request. Hope you will like it.
https://github.com/HybirdCorp/docker-forticlient/pull/5
